# Generated by Django 4.2.4 on 2023-09-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=75)),
                ('descriprion', models.CharField(max_length=500)),
                ('languages', models.CharField(max_length=50)),
                ('frameworks', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='dsf')),
                ('github_link', models.URLField()),
            ],
        ),
    ]
