# Generated by Django 4.2.4 on 2023-09-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projects_options_alter_projects_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=60)),
                ('school', models.CharField(max_length=60)),
                ('link', models.URLField()),
                ('certificate_file', models.FileField(upload_to='certificates_file')),
                ('certicate_photo', models.FileField(upload_to='certificates_photo')),
                ('mark', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
