# Generated by Django 4.2.4 on 2023-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certicate_photo',
            field=models.ImageField(upload_to='certificates_photo'),
        ),
    ]
